# Generated by Django 5.0.1 on 2024-03-18 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcollage', '0002_affiliation_country_course_university_list_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.CreateModel(
            name='Create_Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=40, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('target_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcollage.branch_management')),
                ('employee_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appcollage.employee_role')),
            ],
        ),
    ]
